language: php

php:
  - 7.0

services:
  - mysql
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
- mysql -u root -e 'CREATE DATABASE test_myapp;'
- mysql -u root -e "CREATE USER 'travis'@'localhost' IDENTIFIED BY 'travis';"
- mysql -u root -e "GRANT ALL ON test_myapp.* TO 'travis'@'localhost';"
- composer self-update
- composer install --prefer-source --no-interaction --dev

script:
  - phpunit

notifications:
  email: false