language: php

php:
  - 7.0

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

sudo: false

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('secret') where User='my_app'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo mysql -u my_app -e "CREATE DATABASE test_myapp;"
  - sudo mysql -u my_app -e "GRANT ALL PRIVILEGES ON test_myapp.* TO 'my_app'@'%';";
  - sudo service mysql restart

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit

notifications:
  email: false