language: php

php:
  - 7.0

services:
  - mysql

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

sudo: false

test:
  adapter: mysql2
  database: test_myapp
  username: travis
  encoding: utf8

before_install:
  - mysql -u root -e "CREATE DATABASE test_myapp;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON test_myapp.* TO 'travis'@'%';";

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit

notifications:
  email: false